language: node_js
sudo: false

env:
  - SENECA_VER=@1.x.x
  - SENECA_VER=@2.x.x
  - SENECA_VER=@3.x.x

node_js:
  - "10"
  - "8"

services:
  - redis-server

cache:
  directories:
    - node_modules

after_script:
  npm run coveralls
